# Makefile for ODMSG

CC      := gcc
CFLAGS  := -std=c17 -O2 -Wall -Wextra -pedantic -march=native -flto
LDFLAGS := -flto
TARGET  := odmsg
SRC     := main.c

.PHONY: all clean test

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS) compress.c decompress.c lz_hashchain.c odz_util.c

test: $(TARGET)
	echo 'Hello World' > original
	echo 'ODZ!@!+!!!!!!!!%(&^&-&-&}#!^*&}!!*#&-&%' > odmsgd
	./$(TARGET) c Hello World > encoded
	./$(TARGET) d 'ODZ!@!+!!!!!!!!%(&^&-&-&}#!^*&}!!*#&-&%' > decoded
	cmp original decoded
	cmp odmsgd encoded
	$(RM) original odmsgd encoded decoded

clean:
	$(RM) $(TARGET) *.o
